name: CI

on: 
  pull_request:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: running unit tests
      env:
        MUNCHKIN_ID: ${{ secrets.MUNCHKIN_ID}}
        NEWSLETTER_FORM_ID: ${{secrets.NEWSLETTER_FORM_ID}}
      run:
        npm install
      # run: |
      #   npm install
      #   npm run test:update
      #   npm run test
    - name: running linter
      run: |
        npm install
        npm run test:lint

